"""empty message

Revision ID: 813b179b503b
Revises: 64884b2bd226
Create Date: 2026-05-02 14:54:39.666998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '813b179b503b'
down_revision: Union[str, Sequence[str], None] = '64884b2bd226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('last_weekly_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('monthly_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('last_monthly_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_column('last_monthly_sent_at')
        batch_op.drop_column('monthly_enabled')
        batch_op.drop_column('last_weekly_sent_at')
        batch_op.drop_column('weekly_enabled')

    # ### end Alembic commands ###
